; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.1-LPC-STM32+5 on Sun Jan 23 2022 16:44:38 GMT-0700 (Mountain Standard Time)
; Wait for set temperatures to be reached
M116 P0

